SBP-4367: Hot module reload for plugins
ecobee/sb-kong-vagrant pull request #1
Opened 2019-11-29 15:05 UTC by JonathanLorimer

2019-12-03 15:55 UTC, oaltalabani approved these changes

2019-12-04 09:59 UTC, ioncache requested changes

2019-12-04 09:59 UTC, ioncache commented on hmr.sh
> +  vagrant ssh -c "cd /kong-plugin; luarocks make permission-middleware-0.1-1.rockspec"
```suggestion
  vagrant ssh -c "cd /kong-plugin; luarocks make permission-middleware*.rockspec"
```

2019-12-04 09:59 UTC, ioncache commented on hmr.sh
> +  vagrant ssh -c "cd /tf/dev; echo "yes" | terraform apply"
```suggestion
  vagrant ssh -c "cd /tf/dev; terraform apply -auto-approve"
```

2019-12-04 13:45 UTC, merged